{
    "blocklist-enabled": 0, 
    "download-dir": "\/tmp\/downloads",
    "download-limit": 100, 
    "download-limit-enabled": 0, 
    "encryption": 1, 
    "max-peers-global": 200, 
    "peer-port": 51413, 
    "pex-enabled": 1, 
    "port-forwarding-enabled": 0, 
    "rpc-authentication-required": 1, 
    "rpc-password": "${transmission_password}", 
    "rpc-port": ${transmission_port}, 
    "rpc-username": "${transmission_user}", 
    "rpc-whitelist": "127.0.0.1", 
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/tmp/script.sh",
    "upload-limit": 1, 
    "upload-limit-enabled": 1
}
